$ErrorActionPreference = "Stop"

$repoRaw = "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies.json"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$outFile = Join-Path $root "proxy-data.js"
$metaFile = Join-Path $root "proxy-data-meta.json"

Write-Host "Downloading proxy list from $repoRaw ..."
$raw = Invoke-RestMethod -Uri $repoRaw -UseBasicParsing

$items = foreach ($p in $raw) {
  [PSCustomObject]@{
    protocol = [string]$p.protocol
    host = [string]$p.host
    port = [int]$p.port
    timeout = [double]$p.timeout
    exitIp = if ($p.exit_ip) { [string]$p.exit_ip } else { "" }
    countryCode = if ($p.geolocation.country.iso_code) { [string]$p.geolocation.country.iso_code } else { "" }
    country = if ($p.geolocation.country.names.en) { [string]$p.geolocation.country.names.en } else { "Unknown" }
    city = if ($p.geolocation.city.names.en) { [string]$p.geolocation.city.names.en } else { "" }
    continent = if ($p.geolocation.continent.code) { [string]$p.geolocation.continent.code } else { "" }
    asnOrg = if ($p.asn.autonomous_system_organization) { [string]$p.asn.autonomous_system_organization } else { "" }
  }
}

$ordered = $items | Sort-Object timeout, protocol, country, host
$json = $ordered | ConvertTo-Json -Depth 5 -Compress
$updatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$count = @($ordered).Count

$content = @"
// Auto-generated by update-proxies.ps1
// Source: $repoRaw
// Updated: $updatedAt
// Count: $count
window.PROXYFLOW_DEFAULT_PROXIES = $json;
window.PROXYFLOW_DEFAULT_META = {
  source: "$repoRaw",
  updatedAt: "$updatedAt",
  count: $count
};
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
@{
  source = $repoRaw
  updatedAt = $updatedAt
  count = $count
} | ConvertTo-Json | Set-Content -Path $metaFile -Encoding UTF8

Write-Host "Generated $outFile with $count proxies."
